### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by dsuh93** [MackZumarraga/IdentiStreet#2]
Hey Mack, good job on your schema, just a few comments for your revision:

# Database Schema
​
- [x] Contains correct datatypes
- [x]  Contains appropriate constraints/details
    - [x]  primary key
    - [x]  not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
    - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
​
### Comments
- [x] listings: if you're planning on using decimal numbers for any column (i.e. dollars_per_sq_ft potentially), you need to use a `float` data type. `leasing_launch_date` should probably be a string format unless you plan on using date methods on the data point
- [x] searches: `move_in_date` should be a date object or a string depending on how you'll be using this data point
- [x] tracked_searches: this table seems unnecessary because your searches table already has a foreign key that points to users, what would tracked_searches accomplish? would it return a history of the user's searches? you would definitely be able to just use association with that for the logged in user (i.e. `User.includes(:searches).find_by(id: params[:id])`)

**Comment by MackZumarraga** [comment]
@dsuh93 
-listings: I've decided to go with integer because Streeteasy uses whole numbers for such fields. I've also changed the leasing launch date to string.
-searches: I've changed the type to a date object
-tracked_searches: I wanted to keep this for a button I'll add to save some search (aka filters user used at some point)

**Comment by dsuh93** [comment]
@MackZumarraga 
-tracked_searches: you'd be saving the searches already to the searches table (POST /searches), so the tracked searches doesn't do anything different, you just need to add the searcher_id or user_id to the searches table to show that the search belongs to a specific user

**Comment by MackZumarraga** [comment]
@dsuh93 sounds good; I went ahead and added `saved_search` as a field with type boolean inside of searches table to indicate whether it's a search that I've favorited.

**Comment by dsuh93** [comment]
@MackZumarraga 
great :)
