### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by dsuh93** [MackZumarraga/IdentiStreet#3]
Hey Mack, good work on your backend routes! some comments for revision:

# Backend Routes
​
- [x]  Contains the following sections: HTML, API Endpoints(Backend)
- [x]  Each route has a description
- [x]  API Endpoint routes contains wildcard variables written in `snake_case`
- [x]  Routes does not contain superfluous routes
- [x]  Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    -  i.e. probably don't need a `GET likes` api endpoint because that info comes through the post show
​
### Comments
- [x] missing the static pages root backend route
- [x] users: missing GET request for individual (current) user
- [x] listings: missing POST, PATCH and DELETE routes for listings, you need full CRUD for listings
- [x] searches/tracked_searches: don't need a separate table for tracking searches, include PATCH and DELETE routes for `searches`
- [x] favorited_listings: don't need a GET request just for favorited listings, you can grab that information using associations when grabbing the current user information

**Comment by MackZumarraga** [comment]
@dsuh93 
-listings: will I potentially need a custom route for searches? particularly if the user types in a zipcode or some address in this other search bar.

**Comment by dsuh93** [comment]
@MackZumarraga you can use a GET route for listings according to the search parameter, so potentially you can include another GET request, but with a wildcard, i.e. /api/listings/:filters
